version: '3'
services:
  web:
    restart: always
    build: .
    volumes:
      - ./:/var/www/
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eyetech
    volumes:
      - "./.docker/dbdata:/var/lib/postgresql/data"
  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    depends_on:
      - web
