version: '3'
services:
  web:
    container_name: app_laravel
    restart: always
    build: .
    volumes:
      - ./:/var/www/
    environment:
      SERVICE_NAME: app_laravel
      SERVICE_TAGS: dev
    networks:
      - app_network
  nginx:
    container_name: web_laravel
    build: ./.docker/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    depends_on:
      - web
    networks:
      - app_network
  #MySQL Service Magento2
  db_laravel:
    image: mysql:5.7.22
    container_name: db_laravel
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: eyetech
      MYSQL_USER: eyetech
      MYSQL_PASSWORD: eyetech
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network
  #View Magento2 DB
  phpmyadmin:
    container_name: pma_laravel
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  dbdata:
    driver: local
